### ISSUE TITLE
does it need admin privilige in the origin group?

### ISSUE THREAD

**Issue by zlil** [viperadnan-git/telegram-forwarder-bot#2]
cool stuff!

quick questions:

1. do you need admin permissions in the original group that messages forward from?
2. is there a way to filter messages by the message writer for example?

**Comment by viperadnan-git** [comment]
1. You need admin permissions to add your bot in the channel, for groups you can try adding your bot if they allow. Although you can ask admin to add your bot to the channel.
2. Not yet
