### ISSUE TITLE
Why do I keep getting errors here?

### ISSUE THREAD

**Issue by Npthon** [viperadnan-git/telegram-forwarder-bot#4]
![image_2024-06-07_13-50-37](https://github.com/viperadnan-git/telegram-forwarder-bot/assets/168954190/35d9e0ea-fe04-4d31-825a-bedb58d70506)

An error will be reported when executing the npm run build command. I added ts -e es2015 here and the error will still be reported. The redis database information is accessible.

**Comment by viperadnan-git** [comment]
It's written in bun.sh, It is recommended to use bun for running this app. `bun run bun:start`.

However, I will push an update to resolve this.
